version: '3.4'

networks:
  simulationRunner-network:
    driver: bridge

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: ../BackendAPI/Dockerfile
    networks:
      - simulationRunner-network
    depends_on:
      - postgresHost
#      - simulationrunnerservice
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgresHost:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - simulationRunner-network
#  simulationrunnerservice:
#    image: ${DOCKER_REGISTRY-}simulationrunnerservice
#    build:
#      context: .
#      dockerfile: ../SimulationRunnerService/DockerfileDockerCompose