version: '3.4'

networks:
  simulationRunner-network:
    driver: bridge

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: BackendAPI/Dockerfile
    networks:
      - simulationRunner-network
    depends_on:
      - postgresHost
  postgresHost:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - simulationRunner-network